### ISSUE TITLE
Support for Attach/POST?

### ISSUE THREAD

**Issue by lox** [qnib/doxy#3]
I'd love to be able to proxy container start / container attach. Any plans to support it?

**Comment by smaftoul** [comment]
@lox you closed the issue, have you managed to do it ? 
I added `^.*` to patterns, but the docker client somehow hangs.

**Comment by lox** [comment]
Nope, I built https://github.com/buildkite/sockguard instead

**Comment by smaftoul** [comment]
@lox great, thanks,  I will have a look at it !

**Comment by ChristianKniep** [comment]
Oh, competition... :) Thanks guys for the hint and sorry for not responding.
I started a project to manipulate DockerAPI calls: https://github.com/qnib/moby/blob/houdini/HOUDINI.md
